# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=openradioss-pmi2.yaml

steps:
- name: 'gcr.io/$PROJECT_ID/apptainer'
  args: 
  - 'build'
  - '--fakeroot'
  - '--build-arg' 
  - 'LOCATION=${_LOCATION}'
  - '--build-arg'
  - 'PROJECT_ID=$PROJECT_ID'
  - '--build-arg'
  - 'REPO=${_REPOSITORY}'
  - '--build-arg'
  - 'OMPI4_PMIX_VERSION=${_VERSION}'
  - '--build-arg'
  - 'OPENRADIOSS_VERSION=${_VERSION}'
  - 'openradioss-pmix.sif'
  - 'openradioss-pmix.def'
- name: 'gcr.io/$PROJECT_ID/apptainer'
  args:
  - 'push'
  - 'openradioss-pmix.sif'
  - 'oras://${_LOCATION}/$PROJECT_ID/${_REPOSITORY}/openradioss-pmix:${_VERSION}'
substitutions:
  _LOCATION: us-docker.pkg.dev
  _REPOSITORY: sifs
  _VERSION: latest
