runtime: python312 # Use a supported Python runtime
entrypoint: gunicorn -b :$PORT main:app

# Set an environment variable for the GCS bucket name.
# This is a best practice for configuration.
env_variables:
  GCS_BUCKET_NAME: '<MY_JOBS_BUCKET>' # <-- IMPORTANT: REPLACE THIS
