[default]
args = [
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_01write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_02write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_03write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_04write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_05write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_06write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_07write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_08write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_09write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_10write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_11write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_12write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_13write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_14write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_15write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_16write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_17write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_18write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_19write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_20write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_21write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_22write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_23write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_24write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_25write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_26write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_27write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_28write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_29write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_30write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_31write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_32write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_33write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_34write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_35write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_36write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_37write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_38write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_39write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_40write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_41write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_42write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_43write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_44write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_45write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_46write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
   ["/bin/sh", "-c", "python /data/python_write.py > /data/python_47write${JOB_COMPLETION_INDEX}-${JOB_NAME}.txt"],
]