[default]
#  
project_id = "openfoam-jrt"
platform = "gke-autopilot"
job_prefix = "test-job-"

# Namespace and Service account
service_account_name="default"
namespace="default"

# set container and command
container = {image_uri="python"}
command=["/bin/sh", "-c", "python /data/python_write.py > /data/python_write${JOB_COMPLETION_INDEX}-${JOB_ID}.txt"]

# Limits and config for job
limits={cpu="30m", memory="30Mi", "nvidia.com/gpu"="1"}
node_selector={"cloud.google.com/gke-accelerator"="nvidia-tesla-t4"}
pod_annotations={"gke-gcsfuse/volumes"="true"}

# Mounts, only GCS at this point
volume = {bucketName="k8s_test_jrt", driver="gcsfuse.csi.storage.gke.io"}
volume_mount = {mount_path="/data"}

# Job Indexed or not.
parallelism=10
completion_mode = "Indexed"
#completion_mode = "NonIndexed"
completions=100

# Suspend, must be true for `kueue`
suspend=false
dynaconf_merge = true
