#!/bin/bash
#SBATCH --job-name=MonteCarloMultiGPU
#SBATCH --partition=a2
#SBATCH --output=%3A/out.txt
#SBATCH --error=%3A/err.txt
#SBATCH --time=60

export PROJECT_ID=$(gcloud config get-value project)
# Build SIF, if it doesn't exist
if [[ ! -f montecarlo.sif ]]; then
  export REPOSITORY_URL=oras://us-docker.pkg.dev
  apptainer remote login --username=oauth2accesstoken --password=$(gcloud auth print-access-token) ${REPOSITORY_URL}
  apptainer pull montecarlo.sif oras://us-docker.pkg.dev/${PROJECT_ID}/sifs/montecarlo:latest
fi
for i in {1..100}
do
  apptainer run --nv montecarlo.sif /bin/MonteCarloMultiGPU
done