steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_IMAGE_URI}:${_IMAGE_TAG}', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '${_IMAGE_URI}:${_IMAGE_TAG}' ]
images: [ '${_IMAGE_URI}:${_IMAGE_TAG}' ]
