# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://developer.hashicorp.com/packer/tutorials/docker-get-started/get-started-install-cli
steps:
  - name: 'gcr.io/cloud-builders/wget'
    args: ["https://releases.hashicorp.com/packer/${_PACKER_VERSION}/packer_${_PACKER_VERSION}_linux_amd64.zip"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}',
           '-t', 'gcr.io/$PROJECT_ID/packer',
           '--build-arg', 'PACKER_VERSION=${_PACKER_VERSION}',
           '--build-arg', 'PACKER_VERSION_SHA256SUM=${_PACKER_VERSION_SHA256SUM}',
           '.']
substitutions:
  _PACKER_VERSION: 1.11.0
  _PACKER_VERSION_SHA256SUM: dcac06a4c671bbb71e916da5abe947ebf4d6aa35c197e21c7c7b1d68cb8b7cad

images:
  - 'gcr.io/$PROJECT_ID/packer:latest'
  - 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}'
tags: ['cloud-builders-community']
