#!/bin/bash
#SBATCH --job-name=namd_ipoa1_benchmark
#SBATCH --partition=g2x4
#SBATCH --output=%3A/out_%a.txt
#SBATCH --error=%3A/err.txt
#SBATCH --array=0-1
#SBATCH --gres=gpu:4 
#

dirs=("apoa1_gpu/apoa1_gpuoff_npt.namd" "apoa1_gpu/apoa1_gpuoff_nve.namd")

# Build SIF, if it doesn't exist
if [[ ! -f namd.sif ]]; then
  export NAMD_TAG=3.0-beta5
  apptainer build namd.sif docker://nvcr.io/hpc/namd:$NAMD_TAG 
fi
echo "Running: "  ${dirs[$SLURM_ARRAY_TASK_ID]}
apptainer run --nv namd.sif namd3 +devices 0,1,2,3 +setcpuaffinity ${dirs[$SLURM_ARRAY_TASK_ID]}